# Generated by Django 5.2.1 on 2025-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='skills'),
        ),
    ]
