# Generated by Django 5.2.1 on 2025-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_resume_alter_detail_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='detail',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
